language: rust
dist: bionic
before_install:
  - sudo apt-get update -q
  - sudo apt-get install clang-10 llvm-10-runtime llvm-10-dev llvm-10-tools python3-pip python3-setuptools -y
  - pip3 install mako meson ninja
rust:
  - nightly
  - beta
  - stable
